### ISSUE TITLE
Group intermediate and terminal operations together?

### ISSUE THREAD

**Issue by vickydoosa** [winterbe/sequency#10]
Group intermediate operations together and terminal operations together in the folder structure

```
src/
  intermediate/
    filter.ts
    map.ts
    ...

  terminal/
    reduce.ts
    groupBy.ts

```

**Comment by winterbe** [comment]
Thanks for your feedback. Could you please provide more information. What
benefit would you see in this change other than less files in the src
directory?

I don't see any benefits for end users here.


Vikranth Doosa <notifications@github.com> schrieb am Do. 5. Okt. 2017 um
00:46:

**Comment by winterbe** [comment]
Ping

**Comment by vickydoosa** [comment]
My thinking was it would be easy for developers to quickly add new intermediate or terminal operations.

At first glance when I saw the code, the operations were all over the place. Its not helpful for end users but I thought would be easy to understand for people who contribute.

**Comment by winterbe** [comment]
Thanks for your input. I got your point however I'm not sure if dividing operations on different folders will help navigating the code. But maybe we could take up the issue in PR #14 by splitting interface `SequenceOperators` up into two distinct interfaces `IntermediateOperations` and `TerminalOperations`. 

@couzic What do you think?

**Comment by couzic** [comment]
I agree something could be done to improve the project structure. Also, I believe we can kill two birds with one stone by putting all operations in a specific folder and ignoring that folder when building the docs.
However, I'd rather try to merge PR #14 before adding anything to it, it's already a big chunk in itself. The `SequenceOperators` interface can easily replaced or altered afterwards.

**Comment by winterbe** [comment]
Agree. Let’s tackle this afterwards.

**Comment by couzic** [comment]
PR #14 is merged ! :beers: 

So about folder structure. One thing I would really like to see is all operation implementations in the same folder. They can then be divided into sub-folders, I don't really have an opinion about that. But I think we really need that `operations/` folder.

As I mentioned before, folder structure can be leveraged to improve the docs, right now I'm thinking of hiding all operation implementation classes, along with their modules if possible.

**Comment by winterbe** [comment]
I’m ok was moving all operations into a sub folder. Still not sure about splitting terminal and intermediate operations. Distinction can simply be made by inspecting the function signature: 

Intermediate = Returns Sequence 
Terminal = Returns no Sequence

**Comment by couzic** [comment]
I agree with that. Also, having all operations in one folder dedicated to them makes it quite easy to navigate alphabetically. I fear the terminal VS intermediate discrimination would only make it more confusing.

**Comment by winterbe** [comment]
So let's move all operations to sub-folder `operations`. As for intermediate vs terminal I would suggest that we just describe in the README that all operations returning a `Sequence` are intermediate while all other are `terminal`.

**Comment by winterbe** [comment]
I’ve decided to close this for now. The benefit is rather small and I want to focus on the important parts in my limited spare time.
