### ISSUE TITLE
Sequence.filterNotNull() should return a Sequence<T>, not a Sequence<T | null>

### ISSUE THREAD

**Issue by couzic** [winterbe/sequency#13]
I'll take this one

**Comment by couzic** [comment]
The problem:
```ts
const seq: Sequence<number | null> = ...

const filtered: Sequence<number> = seq.filterNotNull()
```
This code does not compile because filterNotNull() in this case returns a Sequence<number | null>

**Comment by winterbe** [comment]
Thanks. Do you need a new version for that fast? Otherwise I would delay release of this fix until we have more changes to be deployed.

**Comment by couzic** [comment]
No rush, it can wait
