### ISSUE TITLE
SequenceIterator might be migrated to Iterator protocol for performance reasons 

### ISSUE THREAD

**Issue by winterbe** [winterbe/sequency#15]
For code readability reasons (and because I was more used to it) I’ve decided to use the JVM iterator interface for Sequency. 

However for performance reasons using the JavaScript iterator protocol instead could reduce the number of function calls needed to process sequences which might or might not result in better performance for large inputs collections. 

But before we refactor all the code, performance tests should be created to proof that claim.

**Comment by winterbe** [comment]
Benchmark resources: 
- https://calendar.perfplanet.com/2010/bulletproof-javascript-benchmarks/
- https://github.com/bestiejs/benchmark.js

**Comment by geowarin** [comment]
Hey @winterbe !

Thanks again for sequency, it is a very handy and well written lib.
I was heavily inspired by it when writing [kollectionjs](https://github.com/geowarin/kollectionjs).

It follows the exact same API as sequency.
I actually copy-pasted big chunks of your code so most of the credit goes to you ;)
I made sure that the sequency tests were passing on my codebase as well.

The big difference is it uses Iterables and generators all the way.
As a result, the code is 4 times smaller and reads very well, IMHO.

I was curious to see how it would compare to Sequency perf wise.
I used [jsperf](https://jsperf.com/compare-stream/1) for a very quick and dirty comparison.

🥁

**drumrolls**

![image](https://user-images.githubusercontent.com/1045636/33718282-2567d1c0-db5d-11e7-9c42-8e40678ba88d.png)

The benchmark can clearly be improved but the preliminary results tend to be **hugely in favor of Sequency** (at least 4X faster).

I will keep on improving Kollection and probably generators will get faster in the future.
I just wanted to share my findings with you.

Cheers!

**Comment by ShawnTalbert** [comment]
I would be interested in seeing soem sequency performance metrics or benchmarks against similar libraries such as [lazyjs](https://github.com/dtao/lazy.js/)

**Comment by winterbe** [comment]
`SequenceIterator` has been replaced by native `Iterator<T>` protocol to fix #21. As a side effect the code of intermediate operations is now much simpler to read. I'm still interested in proper benchmark tests, but that's subject to future work.
