### ISSUE TITLE
Hide operation implementation classes from public API

### ISSUE THREAD

**Issue by couzic** [winterbe/sequency#17]
Right now, when coding in an IDE (in my case, WebStorm), when I type `Filt`, I get the following auto-complemention suggestions:

- FilterNotNull
- FilterNot
- FilterIndexed
- ...

And by clicking Enter, I can import those classes. It creates unnecessary noise, and it should be easy to prevent that behavior by not generating `.d.ts` files for operator classes.

To do that, I understand we can add the `stripInternal` flag to TypeScript compiler options, and add the `@internal` documentation annotation to classes we want to hide.

It's loosely linked to #10, as the `@internal` annotation may be interpreted by tsdoc as well.

**Comment by winterbe** [comment]
Fully agree on that. Thanks for pointing that out. Sounds like a good solution. We should do it.

**Comment by couzic** [comment]
Well actually, it won't work. The operation implementation classes are the only place where the operation method signatures exist, so removing them from type declaration files will remove all type-safety.

I'm tempted to close this issue and leave it as it is.

The only thing I can think of is renaming the operation classes, with a prefix or suffix, but that would only move the problem elsewhere.

**Comment by winterbe** [comment]
Agree, that renaming is not a proper solution. We had to move all function declarations directly the `Sequence` interface? But I doubt that it's worth the effort because `Sequence` would be bloated and confusing.

**Comment by couzic** [comment]
Right, I'm closing this until someone has a better idea.
