### ISSUE TITLE
New operation `mapTo`

### ISSUE THREAD

**Issue by winterbe** [winterbe/sequency#18]
Kotlin sequences support various `xyzTo()` methods who are terminal variants of intermediate operations such as `map` or `filter`. Those methods are currently not supported in Sequency but are actually quite handy in some situations.

E.g. in React Components you often use `map` to transform a list of things into DOM elements:

```js
items.map(item => (
  <li>{item.text}</li>
)
```

Using sequences you would have to call `toArray()`:

```js
asSequence(items).map(item => (
  <li>{item.text}</li>
).toArray()
```

With `mapTo` the code could be simplified:

```js
asSequence(items).mapTo(item => (
  <li>{item.text}</li>
)
```

`mapTo` could be passed a mutable array as second argument if you want to append the elements to an existing array with a new array as default, if the second argument is omitted.

**Comment by couzic** [comment]
I agree with the general idea. However, `mapTo()` is an operator for `Rx.Observable`, which is widely used these days. Also, it's behavior is completely different, which would make it very confusing.

I suggest to define new operations as:
```ts
asSequence(items).mapToArray(item => (
  <li>{item.text}</li>
)
```
That way the library would be consistent with itself,
```ts
sequence.mapToArray(...)
```
being the strict equivalent to
```ts
sequence.map(...).toArray()
```

**Comment by winterbe** [comment]
Thanks for pointing that out. I agree with you that mapToArray() is a good consistent name for terminal functions like that.

**Comment by winterbe** [comment]
I’m on the road so can’t verify but if in JSX `{iterable}` is supported, we could just make Sequence itself iterable so this would work: `{asSequence(items).map(...)}`.

**Comment by couzic** [comment]
Unfortunately:

`Uncaught Error: Objects are not valid as a React child (found: object with keys {iterator}). If you meant to render a collection of children, use an array instead.`

It would have been awesome though !

**Comment by winterbe** [comment]
Damnit but thanks for testing. 

I want to share some other thoughts:

I vaguely remembered that JSX accepts expression functions. So we could have made Sequences as functions returning result of toArray. However I don’t think it works unless wrapping the result via React.createElement. 

Another way to write would be `{asSequence(items).map(it => ...)()}` but while being shorter it’s quite verbose and not self explaining. 

Different approach could be to provide a utility component (e.g. via separate react-sequency package):

```jsx
<Sequence of={items} unless={predicate}>
  {seq => seq.map(...)}
</Sequence>
```

Last but not it least if Sequence would be a React Element it could be rendered directly. I won’t add React dependency to sequency but maybe this could be achieved via separate package by providing a custom createSequence function?

However I don’t know if it’s worth the effort. 🤷‍♂️

**Comment by winterbe** [comment]
I’m still undecided about mapToArray because we would need to add various ...ToArray methods for every intermediate operation to be complete. That would clutter the API a lot.

**Comment by couzic** [comment]
After using sequency for a while, I'm surprised that the verbosity (compared to Ramda for example) does not bother me at all. Maybe because I used to be a Java developer :)
Just to say that I'm happy with the API as is.

One crazy idea though: a function that would return a function that can transform an array. Something you'd use like:
import {transformArray} from 'sequency'
```ts
const myArrayTransformer = transformArray<TodoItem>()
    .filter(...)
    .sort(...)
    .map(todoItem => <div>{todoItem.title)</div>

const todos: TodoItem[] = [...]

<div>
    { myArrayTransformer(todos) }
</div>
```

Quite a lot of work though !

**Comment by winterbe** [comment]
I know what you mean and I guess I’m going to abandon the idea of
mapToArray to keep the API surface small.

Your idea looks pretty interesting but also looks like a lot of work. Also
keep I mind that you could simply create a function in user code to create
certain sequences for a given input.


Mikael Couzic <notifications@github.com> schrieb am Sa. 18. Nov. 2017 um
14:15:
