### ISSUE TITLE
reduce<S, T extends S> - T extends S does not make sense

### ISSUE THREAD

**Issue by asfernandes** [winterbe/sequency#19]
`reduce` types should be completely unrelated.

**Comment by winterbe** [comment]
`reduce` is different from native `Array.reduce`. Take a look at `fold`:

https://winterbe.github.io/sequency/interfaces/_sequence_.sequence.html#fold

Adriano dos Santos Fernandes <notifications@github.com> schrieb am Mo. 13.
Nov. 2017 um 14:29:
