### ISSUE TITLE
Version 1.0 Roadmap

### ISSUE THREAD

**Issue by winterbe** [winterbe/sequency#2]
Things to finish before releasing 1.0:

- [x] API Doc 
- [x] README
- [x] Website
- [x] Missing operations (dropWhile, takeWhile, ...)

**Comment by MatthiasKunnen** [comment]
This issue has been closed, however, version 1.0 is still not released. What is the reason? Is version 0.10 stable?

**Comment by winterbe** [comment]
The roadmap issue on GitHub was bugged. It included a checklist which was
no longer editable. So I've closed the issue.

1.0 is not available however the API is very solid and stable. I already
use it in production in 3 of my projects.  No breaking changes are planned
for 1.0 besides #3 (chunk) which is not decided yet (feedback welcome).

In order to release 1.0 I want to first implement #5 and get more feedback
from other devs. So feel free to try it out and let me know about any bug
you found (if any).



Matthias Kunnen <notifications@github.com> schrieb am Mo. 11. Sep. 2017 um
00:01:
