### ISSUE TITLE
Type problems with TypeScript 2.6.1

### ISSUE THREAD

**Issue by asfernandes** [winterbe/sequency#20]
I'm using sequency 0.17.0 and TypeScript 2.6.1 with `"noImplicitAny": true` in tsconfig.json, and the ts definition files has errors. This type of definition is not correct:

```ts
any<T>(this: Sequence<T>, predicate?: (T) => boolean): boolean;
```

Correct should be:

```ts
any<T>(this: Sequence<T>, predicate?: (param: T) => boolean): boolean;
```

Errors:
```txt
ERROR in [at-loader] ./node_modules/sequency/lib/all.d.ts:9:43 
    TS7006: Parameter 'T' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/sequency/lib/any.d.ts:9:44 
    TS7006: Parameter 'T' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/sequency/lib/count.d.ts:10:46 
    TS7006: Parameter 'T' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/sequency/lib/filter.d.ts:9:46 
    TS7006: Parameter 'T' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/sequency/lib/first.d.ts:10:46 
    TS7006: Parameter 'T' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/sequency/lib/firstOrNull.d.ts:9:52 
    TS7006: Parameter 'T' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/sequency/lib/firstOrNull.d.ts:16:45 
    TS7006: Parameter 'T' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/sequency/lib/forEach.d.ts:8:44 
    TS7006: Parameter 'T' implicitly has an 'any' type.
```

**Comment by winterbe** [comment]
Thanks for reporting this issue. I guess we could consider enabling
noImplicitAny in Sequency as well.

However you should disable TS compiler for external libraries in your
project by excluding node_modules and enable skipLibCheck compiler option.


Adriano dos Santos Fernandes <notifications@github.com> schrieb am Mo. 13.
Nov. 2017 um 17:50:

**Comment by asfernandes** [comment]
Why do you need to use `any` on he types? With the predicate above, it looks just wrong for me.

And if you really need `any` type, why use it implicitly?

No other library ever required I set skipLibCheck.

**Comment by winterbe** [comment]
I’ll looking into this when I’m back home next week. Stay tuned... 🥁

**Comment by winterbe** [comment]
Sequency now uses `noImplicitAny` compiler setting. All predicates are now properly typed. I'll publish a new release to NPM soon.

**Comment by winterbe** [comment]
Version 0.18 is now available on NPM.

**Comment by couzic** [comment]
:+1:
