### ISSUE TITLE
support for Optional

### ISSUE THREAD

**Issue by egoarka** [winterbe/sequency#26]
This library is missing `Optional` type. Will it be added in the near future in spite of Kotlin api?

I found one suitable with ts support, but it's not about streams
https://github.com/bromne/typescript-optional

**Comment by winterbe** [comment]
No plans to add an optional type to the library.

This library just uses null for absent values which can safely be used in
TypeScript via —strictNullChecks. There’s also a proposal for a safe bill
operator which hopefully gets accepted sooner than later:

https://github.com/tc39/proposal-optional-chaining


egoarka <notifications@github.com> schrieb am Mi. 20. März 2019 um 02:02:
