### ISSUE TITLE
Typescript Generic switching

### ISSUE THREAD

**Issue by WORMSS** [winterbe/sequency#27]
Just wondered if we could get some consistency between return types?
```typescript
map<S, T>(this: Sequence<T>, transform: function): Sequence<S>
```
```typescript
flatMap<S, T>(this: Sequence<S>, transform: function): Sequence<T>
```
I am unsure how many other places this happens, but `S` and `T` have swapped from being the return type and the this type.

**Comment by winterbe** [comment]
Thanks, it's fixed in version 0.20.0.
