### ISSUE TITLE
Add Async feature (from Iterator to AsyncIterableIterator)

### ISSUE THREAD

**Issue by youssefali424** [winterbe/sequency#29]
I was hoping to add async feature to the library and use promises and i found AsyncIterableIterator and implemented it as replacement to iterator and it worked perfectly performance wise was more stable, so i have a suggestion to add an asyncSequence which returns a promise at the end , i already implemented part of it, but i dont have the full time to convert all the sequence operators to implement AsyncIterableIterator instead of iterator, sure doing this in new classes, and do you think it is worth it to add it to the full library as well?

**Comment by youssefali424** [comment]
i am working on it to make async version on this repo [https://github.com/youssefali424/sequency](async-sequency) i would appreciate any review

**Comment by winterbe** [comment]
Sorry I don't have time currently to review your code. I also don't have plans to add async sequences. But feel free to build your own extensions. ✌️

**Comment by youssefali424** [comment]
sure :) thanks for replying i already made a lot of progress, but is it a good idea ? or not?
