### ISSUE TITLE
Make "plus" operator to accept heterogenous types

### ISSUE THREAD

**Issue by couzic** [winterbe/sequency#31]
Hello Benjamin :)

I just used `plus`, and I realized that it is quit strict in the types it accepts:
https://winterbe.github.io/sequency/interfaces/_sequence_.sequence.html#plus

`plus<T>(this: Sequence<T>, other: Sequence<T>): Sequence<T>`

I'd like to have the operator accept an `other` sequence of a different type, the result would be a sequence of a union type. I imagine it would like that:

`plus<A, B>(this: Sequence<A>, other: Sequence<B>): Sequence<A | B>`

I haven't though about it very deeply, so I might not see all the implications yet.

Anyway, if you think it might be a good idea, I'd be willing to work on it and submit a pull request.

Cheers, and good day to you !

**Comment by winterbe** [comment]
Sorry for the late response. This is already possible with the current api:

```ts
sequenceOf<number | string>(1, 2, 3)
    .plus("four")
    .forEach(it => console.log(it));
```
