### ISSUE TITLE
groupBy() returns a Map, not a Sequence

### ISSUE THREAD

**Issue by couzic** [winterbe/sequency#6]
One thing I do quite often with Ramda:

```ts
import {pipe, groupBy, values, map} from 'ramda'

pipe(
  groupBy(person => person.age),
  values,
  map(peopleWithSameAge => ...)
)(people)
```
Often, I use `groupBy()` as an intermediary operation in a long and complex data transformation. But with sequency, I'm forced to do something like:

```ts
asSequence(asSequence(people)
  .groupBy(person => person.age),
  .values())
  .map(peopleWithSameAge => ...)
)
```
It does the job, but fluency is broken. 

I see you already have the concept of `IndexedValue`. We could introduce the concept of `KeyedValue`:
```ts
interface KeyedValue<K extends string, V> {
    key: K
    value: V
}
```
I'm not sure how exactly, but maybe `groupBy()` could return a `Sequence<KeyedValue<...>>`

**Comment by winterbe** [comment]
This is indeed a problem. The same is true for other terminal operations such as `chunk` (see #3). I like your suggestion of `KeyedValue`.

I'd like to stay compatible with the Kotlin API so I don't like the idea of changing `groupBy` to intermediate (returning sequence). But I absolutely see the usecase. Maybe we could provide additional variantions of intermediate operations, e.g. `grouped()` (intermediate) vs `groupBy()` (terminal), `chunked()` (intermediate) vs `chunk()` (terminal) etc.

I've to think about it a few days. Maybe there's a better solution to the problem.

**Comment by geowarin** [comment]
@winterbe I like `groupedBy`vs `groupBy` I wanted to do the exact same thing with [my lib](https://github.com/geowarin/js-streams).

PS: the lib was heavily influenced by stream-js :smile: so it's a nice coincidence that you released sequency. Keep up the great work :+1:

**Comment by winterbe** [comment]
Thanks for your feedback Geoffrey. It's good to see someone's working on a
type safe variant of Java 8 Streams. Keep it up! 👍


Geoffroy Warin <notifications@github.com> schrieb am Do. 14. Sep. 2017 um
17:11:

**Comment by couzic** [comment]
I totally agree with the `groupedBy` VS `groupBy` solution. It makes complete sense to have a declarative formulation for a lazy operation, and an imperative version for a terminal operation. It would make a nice convention for the API.

**Comment by couzic** [comment]
An other idea I'd like to investigate:
```ts
interface AssociativeSequence<K extends string, T> {
    mapValues()
    mapKeys()
    values(): Sequence<T>
    ...
}
```

Maybe we could find a better name for this interface.

**Comment by winterbe** [comment]
I close this issue due to inactivity.
