### ISSUE TITLE
by() and byProp()

### ISSUE THREAD

**Issue by couzic** [winterbe/sequency#7]
sequency relies heavily on accessor functions. Perhaps the API could benefit from the latest TypeScript features. Something like:
```ts
asSequence(people)
  .sorted(
    it => it.nullsLast()
      .thenBy("lastName")
      .thenBy("firstName")
      .thenByDescending("age")
  )
```

The innovation here is that the use of strings is type-safe. The TypeScript compiler checks that `lastName` is a property of `Person`.

Alternatively:
```ts
asSequence(people)
  .sorted(
    it => it.nullsLast()
      .thenByProp("lastName")
      .thenByProp("firstName")
      .thenByPropDescending("age")
  )
```

Also:

```ts
const firstNames: string[] = asSequence(people)
  .select("firstName")
  .toArray()
```

I can help a bit if necessary.

**Comment by winterbe** [comment]
Great idea as long as full type safety is retained! 👍  

As a first step we could evaluate this for comparator composition (`compareBy`, `thenBy`, ...). If it works as expected we could extend all other operations, such as `map`, `associateBy`, etc.

I would prefer not to introduce new method names (`thenByProp`) but instead use method overloading. See here for example:

https://github.com/winterbe/sequency/blob/0354bb2b18177ba6c3d6f691e79d507a719ffc17/src/Sequence.ts#L169-L180

**Comment by couzic** [comment]
I can guarantee 100% type safety :)
Actually, one could argue that using keys is even more type safe, as an accessor function can theoretically return anything.
Agree with starting with comparator composition. I'll see if I can make a pull request tomorrow, or maybe later in the week.
Definitely agree with method overloading, in some cases it can be tricky to maintain type safety but it won't be a problem here.

**Comment by couzic** [comment]
Here's the first pull request:
https://github.com/winterbe/sequency/pull/8

**Comment by winterbe** [comment]
Great work! Thanks for your contribution. I'll publish the changes soon.
