### ISSUE TITLE
Problem with Chained filtering on sublists 

### ISSUE THREAD

**Issue by Siedlerchr** [winterbe/sequency#9]
I am having troubles with filtering on sublists:
I have the following structure which is originated from a json file and is now in an array strucure.
I start with filtering all Frames that have an Event Array, that works as expected.

Now I want to return the frame in which a specific event is.
**Problem**:  It does return the wrong frame, in this case it returns the first Frame, with the Events xxx and yyyy and not bbbb  I also tried adding braces around, but I did not succeed.
Any tips?

```javascript
//myFrames contains all Frames that have an Event 
let allEventFrames = asSequence(myFrames).filterNot(it => isNullOrUndefined(it.Event)).toArray();
let frameWithSpecificEvent = asSequence(allEventFrames).filter(it=>asSequence(it.Event).filter(it=>it.EventDescription.startsWith("bbbb"))).first();
console.log(frameWithSpecificEvent );
```

```json
{
  "Frames": [
    {
      "Metadata": {
      },
      "Event": [
        {
          "EventDescription": "xxxxx"
        },
        {
          "EventDescription": "yyyyy"
        }
      ]
    },
    {
      "Metadata": {
      },
      "Event": [
        {
          "EventDescription": "aaaa"
        },
        {
          "EventDescription": "bbbb"
        }
      ]
    }
  ]
}
```

**Comment by winterbe** [comment]
The outer filter in the last sequence misused. Filter accepts a predicate function which must return a boolean value. But in your case the function returns a sequence which is duck typed to true. That's why the first frame is returned.

**Comment by Siedlerchr** [comment]
Thanks for your answer. I understand the problem. Basically if I apply a flatmap before it works. However, I do not want the object (event) of the inner list, but the Frame as a result. **How would I achieve this?**


My initial idea was drawn from the way how it works with Java 8 streams, where you can easily chain filters, e.g: 
```java
 allFrames.stream().filter(it->it.Event.stream().filter(es->es.EventDescription.equals("bbb"))).findFirst() 
```

**Comment by winterbe** [comment]
I suspect this works in Java 8 streams either.

Try to terminate the interim sequence with a terminal operation such as `any()`.

**Comment by Siedlerchr** [comment]
Thanks for the hint, got it to work:
```
   let firstFrame = asSequence(allEventFrames).filter(it=> {
            return (asSequence(it.Event).filter(it => it.EventDescription.startsWith("bbb"))).any();
        }).first();
```

**Comment by winterbe** [comment]
Glad you solved it. 🥇 

Have fun!
